### ISSUE TITLE
sqlite3 unable to open database file

### ISSUE THREAD

**Issue by Onair-santa** [edrickrenan/telegram-forwarder#5]
Traceback (most recent call last):
  File "C:\Users\anvik\Desktop\tgcf\main.py", line 32, in <module>
    app.run()
  File "C:\Users\anvik\Desktop\tgcf\venv\lib\site-packages\pyrogram\methods\utilities\run.py", line 84, in run
    self.start()
  File "C:\Users\anvik\Desktop\tgcf\venv\lib\site-packages\pyrogram\sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\Users\anvik\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\anvik\Desktop\tgcf\venv\lib\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    is_authorized = await self.connect()
  File "C:\Users\anvik\Desktop\tgcf\venv\lib\site-packages\pyrogram\methods\auth\connect.py", line 40, in connect
    await self.load_session()
  File "C:\Users\anvik\Desktop\tgcf\venv\lib\site-packages\pyrogram\client.py", line 564, in load_session
    await self.storage.open()
  File "C:\Users\anvik\Desktop\tgcf\venv\lib\site-packages\pyrogram\storage\file_storage.py", line 58, in open
    self.conn = sqlite3.connect(str(path), timeout=1, check_same_thread=False)
sqlite3.OperationalError: unable to open database file

**Comment by eliafino** [comment]
Hi, python version? Requirements installed?

**Comment by acinmavi** [comment]
Hey , how did you fix this issue ?
I still got this error when running with both Python 3.8 and 3.11
