### ISSUE TITLE
Strange error and no forwarding

### ISSUE THREAD

**Issue by cloudelfo** [edrickrenan/telegram-forwarder#7]
Until a few days ago, everything was fine Now some messages are not forwarded.

This is the error message
`Task exception was never retrieved
future: <Task finished name='Task-234' coro=<Session.handle_packet() done, defined at /usr/local/lib/python3.8/site-packages/pyrogram/session/session.py:180> exception=ValueError('The server sent an unknown constructor: 0x85d6cbe2\n46d8476d 090738f8 6b60b081 8dccc4e5')>Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyrogram/crypto/mtproto.py", line 76, in unpack
    message = Message.read(data)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/message.py", line 46, in read
    return Message(TLObject.read(BytesIO(body)), msg_id, seq_no, length)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/types/updates_t.py", line 142, in read
    updates = TLObject.read(b)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/primitives/vector.py", line 49, in read
    return List(
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/primitives/vector.py", line 51, in <genexpr>
    else Vector.read_bare(data, size)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/primitives/vector.py", line 40, in read_bare
    return TLObject.read(b)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/types/update_new_channel_message.py", line 60, in read
    message = TLObject.read(b)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
KeyError: 2245446626

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyrogram/session/session.py", line 182, in handle_packet
    data = await self.loop.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/crypto/mtproto.py", line 87, in unpack
    raise ValueError(f"The server sent an unknown constructor: {hex(e.args[0])}\n{left}")
ValueError: The server sent an unknown constructor: 0x85d6cbe2
46d8476d 090738f8 6b60b081 8dccc4e5
Task exception was never retrieved
future: <Task finished name='Task-260' coro=<Session.handle_packet() done, defined at /usr/local/lib/python3.8/site-packages/pyrogram/session/session.py:180> exception=ValueError('The server sent an unknown constructor: 0x85d6cbe2\n48101c73 4fd8526f 8e069cb1')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyrogram/crypto/mtproto.py", line 76, in unpack
    message = Message.read(data)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/message.py", line 46, in read
    return Message(TLObject.read(BytesIO(body)), msg_id, seq_no, length)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/msg_container.py", line 40, in read
    return MsgContainer([Message.read(data) for _ in range(count)])
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/msg_container.py", line 40, in <listcomp>
    return MsgContainer([Message.read(data) for _ in range(count)])
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/message.py", line 46, in read
    return Message(TLObject.read(BytesIO(body)), msg_id, seq_no, length)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/types/updates_t.py", line 142, in read
    updates = TLObject.read(b)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/primitives/vector.py", line 49, in read
    return List(
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/primitives/vector.py", line 51, in <genexpr>
    else Vector.read_bare(data, size)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/primitives/vector.py", line 40, in read_bare
    return TLObject.read(b)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/types/update_new_channel_message.py", line 60, in read
    message = TLObject.read(b)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
KeyError: 2245446626

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyrogram/session/session.py", line 182, in handle_packet
    data = await self.loop.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyrogram/crypto/mtproto.py", line 87, in unpack
    raise ValueError(f"The server sent an unknown constructor: {hex(e.args[0])}\n{left}")
ValueError: The server sent an unknown constructor: 0x85d6cbe2
48101c73 4fd8526f 8e069cb1`

**Comment by cloudelfo** [comment]
With python 3.8 no errors
